import "@repo/ui/integral-cf.css";
import "@repo/ui/satoshi.css";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
