import "@repo/ui/integral-cf.css";
import "@repo/ui/satoshi.css";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import TopHeader from "@/components/TopHeader";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopHeader />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
